### ISSUE TITLE
Intro Section

### ISSUE THREAD

**Issue by paigejo** [paigejo/prelim#1]
Ready for you to read @vnminin (I thought it was due Friday at 10 like the questions document last week)

**Comment by vnminin** [comment]
@paigejo, add your .bib file to git and use only relative file paths in your latex source. Thanks!

**Comment by paigejo** [comment]
@vnminin done!  Also, I incorporated the changes suggested in class.

**Comment by vnminin** [comment]
I am missing "mystyle" file in the root directory.

**Comment by paigejo** [comment]
@vnminin the mystyle file is now in the root directory

**Comment by vnminin** [comment]
got it.
